services:
  - type: web
    name: ai16z-agent
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
