services:
  - type: web
    name: ai16z-agent
    env: node
    buildCommand: |
      apt-get update && \
      apt-get install -y python3 python3-pip && \
      pip3 install yt-dlp && \
      pnpm install && \
      pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
