services:
  - type: web
    name: ai16z-agent
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 23.3.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai16z-db
          property: connectionString

databases:
  - name: ai16z-db
    ipAllowList: []
