services:
  - type: web
    name: ai16z-agent
    env: node
    buildCommand: |
      # System dependencies for Playwright
      apt-get update
      apt-get install -y wget gnupg \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libgbm1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libx11-6 \
        libxcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxrandr2 \
        xvfb \
        build-essential \
        python3

      # Install project dependencies
      pnpm install
      
      # Install Playwright browsers with dependencies
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright pnpm exec playwright install chromium --with-deps
      
      # Build project
      pnpm rebuild
      pnpm build
    startCommand: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 23.3.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai16z-db
          property: connectionString
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    buildFilter:
      paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json

databases:
  - name: ai16z-db
    ipAllowList: []
